### ISSUE TITLE
Update create account UI

### ISSUE THREAD

**Issue by mike-audi** [tiki/recover#16]
If the user selects the create account option. show the create animation (lock) for the time it takes to generate the keys or 2 seconds. whichever is longer.

**Comment by mike-audi** [comment]
![new account](https://user-images.githubusercontent.com/3769672/151108020-fc44c646-5e20-484b-9058-f181945c9a2b.png)
![other device](https://user-images.githubusercontent.com/3769672/151108047-974ca815-5bb0-442c-a455-ed5ba35de602.png)

**Comment by ricardobrg** [comment]
- TODO: fix lottie animation canvas size
